add_newline = true
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
[cmd_duration]
disabled = true
[directory]
read_only = " "
style = "bold blue"
[docker_context]
symbol = " "
[git_branch]
symbol = " "
[git_status]
disabled = true
[nodejs]
detect_extensions = []
not_capable_style = "bold yellow"
[package]
disabled = true
[username]
disabled = true
