add_newline = true
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"
[package]
disabled = true
[line_break]
disabled = true
[cmd_duration]
disabled = true
[directory]
style = "bold blue"
[username]
disabled = true
